package Eligibility_Check_and_Enrolment;


// Import classes
import Classes.*;
// Import other packages
import Course_Recovery_Plan.Course_Admin_Profile_Page;
import Course_Recovery_Plan.Course_Recovery_Plan_Page;
import Course_Recovery_Plan.Login_Page;
import Email_Notification.JavaMailUtil;
import User_Management.LogService;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
// To get the current date and time
import java.time.LocalDateTime;
/**
 *
 * @author yahyanaujid
 */
public class EligibilityFrame extends javax.swing.JFrame {
    
    private User user;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EligibilityFrame.class.getName());
    
    private List<EligibilityStudent> students = new ArrayList<>();

    // Constructor
    public EligibilityFrame(User user) {
        this.user = user;
        
        initBG();
        initComponents();
        loadStudentsFromFiles(); // 1) put some sample students into the list
        loadTable();            // 2) display them in jTable1
        
        // Make function panel fully transparent
        functionPanel.setOpaque(false);
        
        // Call Action Listener for each button
        jButton16.addActionListener(e -> enrol());
        jButton13.addActionListener(e -> {
            new Course_Admin_Profile_Page(user).setVisible(true);
            this.setVisible(false);
        });
        jButton14.addActionListener(e -> {
            new Course_Recovery_Plan_Page(user).setVisible(true);
            this.setVisible(false);
        });
        
        setAutoLogout();
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jFrame2 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jFrame3 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jFrame4 = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton16 = new javax.swing.JButton();
        functionPanel = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setName("jpanel"); // NOI18N

        jButton1.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jButton1.setText("User \nProfile");
        jButton1.setPreferredSize(new java.awt.Dimension(180, 90));

        jButton2.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        jButton2.setText("<html><center>Course<br/>Recovery<br/>Plan<center/><html/>");
        jButton2.setPreferredSize(new java.awt.Dimension(180, 90));

        jButton3.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        jButton3.setText("<html><center>Eligibility<br/>Check and<br/>Enrolment<center/><html/>");
        jButton3.setPreferredSize(new java.awt.Dimension(180, 90));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(98, Short.MAX_VALUE)))
        );

        jFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setName("jpanel"); // NOI18N

        jButton4.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jButton4.setText("User \nProfile");
        jButton4.setPreferredSize(new java.awt.Dimension(180, 90));

        jButton5.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        jButton5.setText("<html><center>Course<br/>Recovery<br/>Plan<center/><html/>");
        jButton5.setPreferredSize(new java.awt.Dimension(180, 90));

        jButton6.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        jButton6.setText("<html><center>Eligibility<br/>Check and<br/>Enrolment<center/><html/>");
        jButton6.setPreferredSize(new java.awt.Dimension(180, 90));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
            .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame2Layout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(98, Short.MAX_VALUE)))
        );

        jFrame3.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setName("jpanel"); // NOI18N

        jButton7.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jButton7.setText("User \nProfile");
        jButton7.setPreferredSize(new java.awt.Dimension(180, 90));

        jButton8.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        jButton8.setText("<html><center>Course<br/>Recovery<br/>Plan<center/><html/>");
        jButton8.setPreferredSize(new java.awt.Dimension(180, 90));

        jButton9.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        jButton9.setText("<html><center>Eligibility<br/>Check and<br/>Enrolment<center/><html/>");
        jButton9.setPreferredSize(new java.awt.Dimension(180, 90));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
            .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame3Layout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(98, Short.MAX_VALUE)))
        );

        jFrame4.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setName("jpanel"); // NOI18N

        jButton10.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jButton10.setText("User \nProfile");
        jButton10.setPreferredSize(new java.awt.Dimension(180, 90));

        jButton11.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        jButton11.setText("<html><center>Course<br/>Recovery<br/>Plan<center/><html/>");
        jButton11.setPreferredSize(new java.awt.Dimension(180, 90));

        jButton12.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        jButton12.setText("<html><center>Eligibility<br/>Check and<br/>Enrolment<center/><html/>");
        jButton12.setPreferredSize(new java.awt.Dimension(180, 90));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
            .addGroup(jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jFrame4Layout.setVerticalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame4Layout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(98, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eligibility Check and Enrolment");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "No. of Failed Courses", "CGPA", "Year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(70);
        }

        jButton16.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jButton16.setText("Enroll");

        jButton15.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jButton15.setForeground(new java.awt.Color(51, 51, 51));
        jButton15.setText("<html><center>Eligibility<br/>Check and<br/>Enrollment<center/><html/>");
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.setPreferredSize(new java.awt.Dimension(180, 90));

        jButton14.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        jButton14.setForeground(new java.awt.Color(153, 153, 153));
        jButton14.setText("<html><center>Course<br/>Recovery<br/>Plan<center/><html/>");
        jButton14.setPreferredSize(new java.awt.Dimension(180, 90));

        jButton13.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        jButton13.setForeground(new java.awt.Color(153, 153, 153));
        jButton13.setText("User \nProfile");
        jButton13.setPreferredSize(new java.awt.Dimension(180, 90));

        javax.swing.GroupLayout functionPanelLayout = new javax.swing.GroupLayout(functionPanel);
        functionPanel.setLayout(functionPanelLayout);
        functionPanelLayout.setHorizontalGroup(
            functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(functionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        functionPanelLayout.setVerticalGroup(
            functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(functionPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton16)
                .addContainerGap())
            .addComponent(functionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(functionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Method 1: Change the background
    private void initBG() {
        // Get the path of background image
        Background background = new Background("C:\\Users\\yu en\\OneDrive\\Documents\\Y2S1\\OODJ\\Assignment\\images\\interfaceBG.jpg");

        // allow components on top of the background
        background.setLayout(null);

        // Use this panel as the whole page
        setContentPane(background);
    }
    
     // Load real students from CourseDB.txt, StudentDB.txt and StudentGradeDB.txt
    private void loadStudentsFromFiles() {
    students.clear();

    // ---------- STEP 1: Load course credits from CourseDB ----------
    // courseID -> credits
    Map<String, Integer> courseCredits = new HashMap<>();

    try (BufferedReader br = new BufferedReader(new FileReader("src/Eligibility_Check_and_Enrolment/CourseDB.txt"))) {
        String line = br.readLine(); // header: courseID,courseName,credits,...
        while ((line = br.readLine()) != null) {
            line = line.trim();
            if (line.isEmpty() || line.startsWith("...")) {
                continue;
            }

            String[] parts = line.split(",");
            if (parts.length < 3) {
                continue;
            }

            String courseID = parts[0].trim();
            int credits;

            try {
                credits = Integer.parseInt(parts[2].trim());
            } catch (NumberFormatException e) {
                continue;
            }

            courseCredits.put(courseID, credits);
        }
    } catch (IOException ex) {
        logger.log(java.util.logging.Level.SEVERE, "Error reading CourseDB.txt", ex);
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Error loading CourseDB.txt. Please make sure the file exists.",
                "File Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    // ---------- STEP 2: Load basic student info from StudentDB ----------
    // studentID -> Student object (name + level + status)
    Map<String, EligibilityStudent> studentMap = new HashMap<>();

    try (BufferedReader br = new BufferedReader(new FileReader("src/Eligibility_Check_and_Enrolment/StudentDB.txt"))) {
        String line = br.readLine(); // header: studentID,firstName,lastName,major,year,email
        while ((line = br.readLine()) != null) {
            line = line.trim();
            if (line.isEmpty() || line.startsWith("...")) {
                continue;
            }

            String[] parts = line.split(",");
            if (parts.length < 6) {
                continue;
            }

            String studentID = parts[0].trim();
            String firstName = parts[1].trim();
            String lastName  = parts[2].trim();
            String yearText  = parts[4].trim(); // Freshman / Sophomore / Junior / Senior
            // we ignore major + email for this screen

            String fullName = firstName + " " + lastName;
            int level = convertYearToLevel(yearText);

            // cgpa & fails will be filled later
            EligibilityStudent s = new EligibilityStudent(studentID,fullName, level);
            studentMap.put(studentID, s);
        }
    } catch (IOException ex) {
        logger.log(java.util.logging.Level.SEVERE, "Error reading StudentDB.txt", ex);
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Error loading StudentDB.txt. Please make sure the file exists.",
                "File Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    // ---------- STEP 3: Process StudentGradeDB to compute CGPA + fails ----------
    // We accumulate:
    //   totalGradePoints[studentID] = sum(gradePoint * credits)
    //   totalCredits[studentID]     = sum(credits)
    //   failedCounts[studentID]     = number of 'F' grades

    Map<String, Double> totalGradePoints = new HashMap<>();
    Map<String, Integer> totalCredits = new HashMap<>();
    Map<String, Integer> failedCounts = new HashMap<>();

    try (BufferedReader br = new BufferedReader(new FileReader("src/Eligibility_Check_and_Enrolment/StudentGradeDB.txt"))) {
        String line = br.readLine(); // header: gradeID,studentID,courseID,year,gradePoint,grade
        while ((line = br.readLine()) != null) {
            line = line.trim();
            if (line.isEmpty() || line.startsWith("...")) {
                continue;
            }

            String[] parts = line.split(",");
            if (parts.length < 6) {
                continue;
            }

            String gradeID   = parts[0].trim(); // unused, just for info
            String studentID = parts[1].trim();
            String courseID  = parts[2].trim();
            String yearText  = parts[3].trim(); // not used here
            String gradePointStr = parts[4].trim();
            String letterGrade   = parts[5].trim(); // e.g. A, B+, C-, F

            // Only process if we know this student and this course exists
            if (!studentMap.containsKey(studentID)) {
                continue;
            }
            if (!courseCredits.containsKey(courseID)) {
                continue; // no credits info → skip
            }

            int credits = courseCredits.get(courseID);
            double gradePoint;
            try {
                gradePoint = Double.parseDouble(gradePointStr);
            } catch (NumberFormatException e) {
                continue;
            }

            // total grade points = sum(gradePoint * credits)
            double currentTGP = totalGradePoints.getOrDefault(studentID, 0.0);
            totalGradePoints.put(studentID, currentTGP + gradePoint * credits);

            // total credits = sum(credits)
            int currentCredits = totalCredits.getOrDefault(studentID, 0);
            totalCredits.put(studentID, currentCredits + credits);

            // failed course: letterGrade == "F"
            // failed course if gradePoint < 2.0
            if (gradePoint < 2.0) {
                int currentFails = failedCounts.getOrDefault(studentID, 0);
                failedCounts.put(studentID, currentFails + 1);
            }
        }
    } catch (IOException ex) {
        logger.log(java.util.logging.Level.SEVERE, "Error reading StudentGradeDB.txt", ex);
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Error loading StudentGradeDB.txt. Please make sure the file exists.",
                "File Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    // ---------- STEP 4: Calculate CGPA + failed courses and fill Student list ----------
    for (String studentID : studentMap.keySet()) {
        EligibilityStudent s = studentMap.get(studentID);

        double tgp = totalGradePoints.getOrDefault(studentID, 0.0);
        int tch    = totalCredits.getOrDefault(studentID, 0);
        int fails  = failedCounts.getOrDefault(studentID, 0);

        double cgpa = 0.0;
        if (tch > 0) {
            cgpa = tgp / tch;
        }

        s.setCgpa(cgpa);
        s.setFailedCourses(fails);

        students.add(s);
    }
}
    
        // Convert academic year text from StudentDB to a numeric level
    // 1 = Freshman, 2 = Sophomore, 3 = Junior, 4 = Senior
    private int convertYearToLevel(String year) {
        if (year == null) {
            return 1;
        }
        year = year.trim().toLowerCase();
        switch (year) {
            case "freshman":
                return 1;
            case "sophomore":
                return 2;
            case "junior":
                return 3;
            case "senior":
                return 4;
            default:
                return 1; // safe default if something weird is in the file
        }
    }
    
        // Temporary test data (later you replace this with Yu En's database)
    
    private void loadTable() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    for (EligibilityStudent s : students) {
        model.addRow(new Object[] {
            s.getStudentID(),
            s.getName(),
            s.getFailedCourses(),
            String.format("%.2f", s.getCgpa()),
            s.getYearText()  // shows Freshman, Sophomore, Junior, Senior, Graduated
        });
    }
}

    // helper: find Student object by ID
    private EligibilityStudent findStudentById(String studentID) {
    for (EligibilityStudent s : students) {
        if (studentID != null && studentID.equals(s.getStudentID())) {
            return s;
        }
    }
    return null;
}

    // helper: rewrite StudentDB.txt updating the year field for students we have in memory
    private void saveStudentsToFile() {
    java.io.File file = new java.io.File("data/StudentDB.txt");
    java.util.List<String> outputLines = new java.util.ArrayList<>();

    try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(file))) {
        String header = br.readLine();
        if (header != null) {
            outputLines.add(header); // keep header
        }
        String line;
        while ((line = br.readLine()) != null) {
            if (line.trim().isEmpty()) {
                outputLines.add(line);
                continue;
            }
            String[] parts = line.split(",", -1); // keep empty tokens
            if (parts.length < 6) {
                // malformed line — keep as-is
                outputLines.add(line);
                continue;
            }
            String studentID = parts[0].trim();
            EligibilityStudent s = findStudentById(studentID);
            if (s != null) {
                // Replace the year field (index 4) with the current year text
                parts[4] = s.getYearText();
                outputLines.add(String.join(",", parts));
            } else {
                outputLines.add(line);
            }
        }
    } catch (java.io.IOException ex) {
        logger.log(java.util.logging.Level.SEVERE, "Error reading StudentDB.txt for saving", ex);
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Failed to read StudentDB.txt while saving. Changes were not saved.",
                "Save Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    // Write back (overwrite)
    try (java.io.PrintWriter pw = new java.io.PrintWriter(new java.io.FileWriter(file, false))) {
        for (String l : outputLines) {
            pw.println(l);
        }
    } catch (java.io.IOException ex) {
        logger.log(java.util.logging.Level.SEVERE, "Error writing StudentDB.txt", ex);
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Failed to write StudentDB.txt. Changes were not saved.",
                "Save Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
}
    
    private void enrol() {
        // 1) Check if a row is selected
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            // No row selected
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please select a student first.",
                    "No Student Selected",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return; // stop here
        }

        // 2) Get the Student object that matches this row
        EligibilityStudent selectedStudent = students.get(selectedRow);

        // 3) Check eligibility using your lecturer's rule
        if (!selectedStudent.isEligible()) {
            // Not eligible -> show error page (dialog)
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "This student does not meet the criteria for progression.\n"
                  + "Please select another student.",
                    "Enrollment Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return; // stop here
        }

        // 4) Eligible -> ask for confirmation
        int choice = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "You are about to enroll this student to the next level.\n"
              + "Are you sure you want to proceed?",
                "Confirm Enrollment",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (choice != javax.swing.JOptionPane.YES_OPTION) {
            // User clicked NO -> do nothing
            return;
        }

        // 5) Progress the student (move level or mark Graduated)
        selectedStudent.progress();
        saveStudentsToFile();
        loadTable();

        // (Optional) If you later show level/status in table, you would call:
        // loadTable();

        // 6) Show success message
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "You have successfully enrolled this student.",
                "Enrollment Successful",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
    
        StudentService ss = new StudentService();
        // Get the array of all rows from StudentDB
        Classes.Student[] student = ss.loadData();
        
        // Call Email Service
        EmailService es = new EmailService();
        
        // To store recepient email
        String recipientEmail = "";
        
        // Loop through every row in student array
        for(int i = 0; i < student.length; i++) {
            // Check which row matches the studentID that is passed in
            if(student[i].getStudentID().equals(selectedStudent.getStudentID())) {
                // Get the student email
                recipientEmail = student[i].getEmail();
            }
        }
        
        // Set subject for email header
        String subject = "Your New Academic Year Is Now Active";
        // Set text message for the email body
        String textMessage = "Dear Student,\n\n"
                + "You have been successfully enrolled into the new year. Please log in to your APSpace to check your updated timetable.\n\n"
                + "If you have any questions, feel free to reach out.\n\n"
                + "Best regards";
        
        es.joinEmail(recipientEmail, subject);
        // Call sendMail method in JavaMailUtil to send notification to the student
        JavaMailUtil.sendMail(recipientEmail, subject, textMessage);
    }
    
    // Method: When user terminate system, the log will also be saved
    private void setAutoLogout() {
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e) {
                // Get the current date and time
                LocalDateTime logoutTime = LocalDateTime.now();
                // Call writeLog method to save the log into database
                LogService.writeLog(Login_Page.currentUserID, Login_Page.loginTime, logoutTime);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel functionPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
