package User_Management;

// Import Classes
import Classes.*;
// Import other packages
import Course_Recovery_Plan.Login_Page;
import Email_Notification.JavaMailUtil;

import javax.swing.JOptionPane;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.File;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fadla
 */
public class AddUserConfirmationPage extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(AddUserConfirmationPage.class.getName());

    private static final String USER_DB_PATH =
            "C:\\Users\\yu en\\OneDrive\\Documents\\Y2S1\\OODJ\\Assignment\\data\\UserDB.txt";

    // data coming from Userpage
    private String username;
    private String password;
    private String title;
    private String email;
    private String role;
    private AddUserPage add_page;
    private User user;

    // Constructor
    public AddUserConfirmationPage(String username, String password,
                                   String title, String email, String role, AddUserPage add_page, User user) {
        this.username = username;
        this.password = password;
        this.title    = title;
        this.email    = email;
        this.role     = role;
        this.add_page = add_page;
        this.user = user;

        initComponents();
        
        // Call Action Listener for each button
        jButton2.addActionListener(e -> setVisible(false));
        jButton1.addActionListener(e -> yesClicked());
        
        setAutoLogout();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add User?");

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel1.setText("You are about to add this user  ");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel2.setText("Are you sure?");

        jButton1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jButton1.setText("Yes");

        jButton2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jButton2.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2))
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yesClicked() {
        // basic safety check
        if (username == null || password == null || title == null ||
            email == null || role == null) {

            JOptionPane.showMessageDialog(this,
                    "User data is missing. Please add from the Userpage again.");
            new UserManagementPage(user).setVisible(true);
            this.dispose();
            return;
        }

        try {
            String newUserId = getNextUserId();   // generate next ID, e.g. U011
            String status = "Active";

            // Format: userID,username,password,title,emailAddress,role,status
            String line = String.join(",", newUserId, username, password,
                                       title, email, role, status);

            // Step 1: Read existing lines & remove ALL empty rows
            List<String> lines = new ArrayList<>();
            try (BufferedReader br = new BufferedReader(new FileReader(USER_DB_PATH))) {
                String existing;
                while ((existing = br.readLine()) != null) {
                    if (!existing.trim().isEmpty()) {        // skip blank lines
                        lines.add(existing);
                    }
                }
            }

            // Step 2: Add the new user line
            String newUserLine = String.join(",", newUserId, username, password,
                                             title, email, role, status);
            lines.add(newUserLine);

            // Step 3: Rewrite the file WITHOUT any empty lines
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(USER_DB_PATH, false))) {
                for (int i = 0; i < lines.size(); i++) {
                    bw.write(lines.get(i));
                    if (i < lines.size() - 1) {              // avoid trailing blank line
                        bw.newLine();
                    }
                }
            }

            JOptionPane.showMessageDialog(this,
                    "User added successfully with ID: " + newUserId);
            
            // Call Email Service
            EmailService es = new EmailService();
            
            String subject = "Your Account Has Been Created";
            String textMessage = "Dear User,\n\n"
                + "Your account has been successfully created. You may now log in to the system.\n\n"
                + "If you have any questions, feel free to reach out.\n\n"
                + "Best regards";
            
            es.joinEmail(this.email, subject);
            // Call sendMail method in JavaMailUtil to send notification to the student
            JavaMailUtil.sendMail(this.email, subject, textMessage);

            // Back to User Management page
            UserManagementPage management_page = new UserManagementPage(user);
            management_page.setVisible(true);
            add_page.setVisible(false);
            this.dispose();

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error writing to UserDB.txt:\n" + ex.getMessage(),
                    "File Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // ===== helper: get next user ID from UserDB.txt =====
    private String getNextUserId() throws IOException {
        File file = new File(USER_DB_PATH);

        if (!file.exists()) {
            // if file missing, first ID is U001
            return "U001";
        }

        String lastId = "U000";  // default if only header exists

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line = br.readLine(); // header
            if (line == null) {
                return "U001";
            }

            while ((line = br.readLine()) != null) {
                if (!line.trim().isEmpty()) {
                    String[] parts = line.split(",");
                    if (parts.length > 0) {
                        lastId = parts[0].trim(); // first column = userID
                    }
                }
            }
        }

        int num = Integer.parseInt(lastId.substring(1)); // remove 'U'
        num++;
        return String.format("U%03d", num);  // U001, U002, ...
    }

    // Method: When user terminate system, the log will also be saved
    private void setAutoLogout() {
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e) {
                // Get the current date and time
                LocalDateTime logoutTime = LocalDateTime.now();
                // Call writeLog method to save the log into database
                LogService.writeLog(Login_Page.currentUserID, Login_Page.loginTime, logoutTime);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
