package User_Management;

// Import classes
import Classes.*;
import Course_Recovery_Plan.Login_Page;
// Import other packages
import Email_Notification.JavaMailUtil;

import javax.swing.JOptionPane;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.File;
import java.io.IOException;
import java.time.LocalDateTime;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fadla
 */

public class DeactivateUserConfirmationPage extends javax.swing.JFrame {

    private String userID;
    private User user;
    private String deactivatedUserEmail;
    private UserManagementPage management_page;
    
  private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(DeactivateUserConfirmationPage.class.getName());

       // <-- THIS IS THE CORRECT PLACE

   // Constructor
    public DeactivateUserConfirmationPage(String userID, User user, UserManagementPage management_page) {
        this.userID = userID;   // ✔ store the selected userID
        this.user = user;
        this.management_page = management_page;
        
        initComponents();

        // Call Action Listener for each button
        jButton2.addActionListener(e -> setVisible(false));
        jButton1.addActionListener(e -> yesClicked());
        
        setAutoLogout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Deactivate User?");

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel1.setText("You are about to deactivate this user  ");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel2.setText("Are you sure?");

        jButton1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jButton1.setText("Yes");

        jButton2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jButton2.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yesClicked() {
        if (userID == null || userID.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No user selected to deactivate.");
        return;        // TODO add your handling code here:
    }                                        

  String filePath = "C:\\Users\\yu en\\OneDrive\\Documents\\Y2S1\\OODJ\\Assignment\\data\\UserDB.txt";

    File inputFile = new File(filePath);
    File tempFile  = new File(inputFile.getParent(), "UserDB_temp.txt");

    try (BufferedReader reader = new BufferedReader(new FileReader(inputFile));
         BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile))) {

        // Read header (if any)
        String headerLine = reader.readLine();
        if (headerLine == null) {
            JOptionPane.showMessageDialog(this, "User DB is empty.");
            return;
        }

        // Write header back
        writer.write(headerLine);
        writer.newLine();

        // Find the index of the "Status" column if header contains it
        String[] headers = headerLine.split(",", -1);
        int statusIndex = -1;
        for (int i = 0; i < headers.length; i++) {
            if ("status".equalsIgnoreCase(headers[i].trim())) {
                statusIndex = i;
                break;
            }
        }
        // if no explicit Status column, we'll append/update the last column

        // Process data rows and update status for matching userID
        String line;
        boolean found = false;
        deactivatedUserEmail = null;
        while ((line = reader.readLine()) != null) {
            if (line.trim().isEmpty()) {
                writer.newLine();
                continue;
            }

            String[] parts = line.split(",", -1);
            String id = parts.length > 0 ? parts[0].trim() : "";

            if (id.equals(userID)) {
                found = true;
                
                if (parts.length > 4) {
                    deactivatedUserEmail = parts[4].trim();
                }
                
                // Ensure parts array is large enough
                if (statusIndex >= 0) {
                    if (statusIndex >= parts.length) {
                        String[] expanded = new String[statusIndex + 1];
                        System.arraycopy(parts, 0, expanded, 0, parts.length);
                        for (int i = parts.length; i < expanded.length; i++) expanded[i] = "";
                        parts = expanded;
                    }
                    parts[statusIndex] = "Deactivated";
                } else {
                    // append or replace last column
                    if (parts.length == 0) {
                        parts = new String[] { userID, "", "", "", "", "", "Deactivated" };
                    } else {
                        String[] expanded = new String[Math.max(parts.length, 7)];
                        System.arraycopy(parts, 0, expanded, 0, parts.length);
                        for (int i = parts.length; i < expanded.length; i++) expanded[i] = "";
                        expanded[expanded.length - 1] = "Deactivated";
                        parts = expanded;
                    }
                }
                writer.write(String.join(",", parts));
                writer.newLine();
            } else {
                // write line unchanged
                writer.write(line);
                writer.newLine();
            }
        }

        if (!found) {
            // optional: inform user if ID wasn't found
            JOptionPane.showMessageDialog(this, "User ID " + userID + " not found in DB.");
        }

    } catch (IOException ex) {
        JOptionPane.showMessageDialog(this,
                "Failed to update user status:\n" + ex.getMessage());
        return;
    }

    // Replace original file with the temp file (atomic-ish)
    if (!inputFile.delete()) {
        // if delete fails, try to continue; attempt rename may also fail
        System.err.println("Warning: could not delete original file: " + inputFile.getAbsolutePath());
    }
    if (!tempFile.renameTo(inputFile)) {
        JOptionPane.showMessageDialog(this,
                "Failed to replace original user DB file. Please check file permissions.");
        return;
    }

    JOptionPane.showMessageDialog(this, "User " + userID + " has been deactivated.");
    
    // Call Email Service
    EmailService es = new EmailService();
    
    String subject = "Your Account Has Been Deactivated";
    String textMessage = "Dear User,\n\n"
        + "Please be informed that your account has been deactivated.\n\n"
        + "If you have any questions, feel free to reach out.\n\n"
        + "Best regards";
            
    es.joinEmail(deactivatedUserEmail, subject);
    // Call sendMail method in JavaMailUtil to send notification to the student
    JavaMailUtil.sendMail(deactivatedUserEmail, subject, textMessage);

    management_page.setVisible(false);
    UserManagementPage new_management_page = new UserManagementPage(user);
    new_management_page.setVisible(true);
    this.setVisible(false);
    }
    
    // Method: When user terminate system, the log will also be saved
    private void setAutoLogout() {
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e) {
                // Get the current date and time
                LocalDateTime logoutTime = LocalDateTime.now();
                // Call writeLog method to save the log into database
                LogService.writeLog(Login_Page.currentUserID, Login_Page.loginTime, logoutTime);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}

