package User_Management;

// Import Classes
import Classes.*;
import Course_Recovery_Plan.Login_Page;
// Import other packages
import Email_Notification.JavaMailUtil;

import javax.swing.JOptionPane;
import java.io.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fadla
 */
public class UpdateUserConfirmationPage extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(UpdateUserConfirmationPage.class.getName());

    private static final String USER_DB_PATH =
            "C:\\Users\\yu en\\OneDrive\\Documents\\Y2S1\\OODJ\\Assignment\\data\\UserDB.txt";

    // Data coming from Updatepage
    private String userID;
    private String username;
    private String password;
    private String title;
    private String email;
    private String role;
    private String status;
    private UpdateUserPage update_page;
    private User user;

    /** Constructor called from Update page with real data */
    public UpdateUserConfirmationPage(String userID, String username, String password,
                                      String title, String email, String role, String status, UpdateUserPage update_page, User user) {
        this.userID = userID;
        this.username = username;
        this.password = password;
        this.title = title;
        this.email = email;
        this.role = role;
        this.status = status;
        this.update_page = update_page;
        this.user = user;

        initComponents();
        
        // Call Action Listener for each button
        jButton2.addActionListener(e -> setVisible(false));
        jButton1.addActionListener(e -> yesClicked());
        
        setAutoLogout();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update User?");

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel1.setText("You are about to update this user  ");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel2.setText("Are you sure?");

        jButton1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jButton1.setText("Yes");

        jButton2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jButton2.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(108, 108, 108)
                        .addComponent(jButton2)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void yesClicked() {
        // Safety: if userID is empty, don't try to update
        if (userID == null || userID.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No user data to update. Did you open this page directly?");
            return;
        }

        ArrayList<String> lines = new ArrayList<>();

        try (BufferedReader br = new BufferedReader(new FileReader(USER_DB_PATH))) {
            String header = br.readLine();   // keep header line
            if (header != null) {
                lines.add(header);
            }

            String line;
            while ((line = br.readLine()) != null) {
                if (line.trim().isEmpty()) continue;

                String[] parts = line.split(",");
                // first column is userID
                if (parts.length > 0 && parts[0].trim().equals(userID)) {
                    // build updated line
                    String updatedLine = String.join(",",
                            userID, username, password, title, email, role, status);
                    lines.add(updatedLine);
                } else {
                    lines.add(line);
                }
            }

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error reading UserDB.txt:\n" + ex.getMessage());
            return;
        }

        // write all lines back
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(USER_DB_PATH))) {
            for (String l : lines) {
                bw.write(l);
                bw.newLine();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error writing UserDB.txt:\n" + ex.getMessage());
            return;
        }

        JOptionPane.showMessageDialog(this, "User updated successfully!");

        // Call Email Service
        EmailService es = new EmailService();
        
        String subject = "Your Account Has Been Updated";
        String textMessage = "Dear User,\n\n"
            + "Your account has been updated successfully. You may now log in to the system.\n\n"
            + "If you have any questions, feel free to reach out.\n\n"
            + "Best regards";

        es.joinEmail(this.email, subject);
        // Call sendMail method in JavaMailUtil to send notification to the student
        JavaMailUtil.sendMail(this.email, subject, textMessage);

        // return to User management page
        UserManagementPage management_page = new UserManagementPage(user);
        management_page.setVisible(true);
        update_page.setVisible(false);
        this.setVisible(false);
    }
    
    // Method: When user terminate system, the log will also be saved
    private void setAutoLogout() {
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e) {
                // Get the current date and time
                LocalDateTime logoutTime = LocalDateTime.now();
                // Call writeLog method to save the log into database
                LogService.writeLog(Login_Page.currentUserID, Login_Page.loginTime, logoutTime);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}